"""
Django settings for gestion_clubs project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import dj_database_url
from decouple import config
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-0f#7e5x1gq)ji8yk8@4rruydvx4bd^+!e2i&d%yoov(eiunyz4'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',

    'rest_framework_simplejwt.token_blacklist',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',

    'accounts',
    'clubs',

    'cloudinary_storage',
    'cloudinary',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', 
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gestion_clubs.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gestion_clubs.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

#
# Configuration du Jeton
# 

from datetime import timedelta

SIMPLE_JWT = {
    # Le token d'accès expire après 1 jour
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    # Le token de rafraîchissement expire après 7 jours
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    # Le token de refresh est renouvelé à chaque utilisation
    'ROTATE_REFRESH_TOKENS': True,
    # L'ancien refresh token est blacklisté après rotation
    'BLACKLIST_AFTER_ROTATION': True,
    # L'algorithme de signature du token
    'ALGORITHM': 'HS256',
    # Le type du token dans le header Authorization
    'AUTH_HEADER_TYPES': ('Bearer',),
}


# 
# Configuration DRF (Django REST Framework)
# 
REST_FRAMEWORK = {
    # Par défaut, toutes les routes nécessitent une authentification
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}


# 
# CORS — Autoriser Angular à communiquer avec Django
#
CORS_ALLOWED_ORIGINS = [
    "http://localhost:4200",  # Port par défaut d'Angular
    'https://gestion-clubs-frontend.vercel.app',
]

CORS_ALLOWED_CREDENTIALS = True

AUTH_USER_MODEL = 'accounts.Utilisateur'

import os
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'



# ── Sécurité ──────────────────────────────────────────────────────
SECRET_KEY = config('SECRET_KEY', default='ta-cle-actuelle')
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'gestion-clubs-backend-1.onrender.com',  # autorise tous les sous-domaines Render
]

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'