# Generated by Django 4.2.19 on 2026-05-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='Utilisé comme identifiant de connexion', max_length=254, unique=True, verbose_name='Adresse email')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de famille')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('role', models.CharField(choices=[('visiteur', 'Visiteur'), ('membre', 'Membre'), ('administrateur', 'Administrateur')], default='visiteur', max_length=20, verbose_name='Rôle dans le système')),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='profils/', verbose_name='Photo de profil')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('is_active', models.BooleanField(default=True, help_text='Désactivez pour bannir un utilisateur sans le supprimer', verbose_name='Compte actif')),
                ('is_staff', models.BooleanField(default=False, help_text='Donne accès au panneau /admin de Django', verbose_name='Accès admin Django')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'utilisateurs',
            },
        ),
    ]
