# Generated by Django 4.2.19 on 2026-05-27 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('club_soumis', 'Nouveau club en attente de validation'), ('club_valide', 'Club validé'), ('club_rejete', 'Club rejeté'), ('club_suspendu', 'Club suspendu'), ('publication_soumise', 'Nouvelle publication en attente'), ('publication_validee', 'Publication validée'), ('publication_rejetee', 'Publication rejetée'), ('membre_ajoute', 'Vous avez été ajouté à un club')], max_length=50, verbose_name='Type de notification')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Contenu du message')),
                ('est_lue', models.BooleanField(default=False, verbose_name='Notification lue')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-date_creation'],
            },
        ),
    ]
