# Generated by Django 4.2.19 on 2026-05-27 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True, verbose_name='Nom du club')),
                ('mission', models.TextField(verbose_name='Mission / Description du club')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clubs/logos/', verbose_name='Logo du club')),
                ('filiere', models.CharField(choices=[('genie_logiciel', 'Génie Logiciel'), ('reseaux_telecom', 'Réseaux & Télécommunications'), ('genie_civil', 'Génie Civil'), ('comptabilite', 'Comptabilité'), ('marketing', 'Marketing'), ('toutes_filieres', 'Toutes filières')], default='genie_logiciel', max_length=150, verbose_name='Filière associée')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('suspendu', 'Suspendu'), ('archive', 'Archivé')], default='en_attente', max_length=20, verbose_name='Statut du club')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name="Date de validation par l'admin")),
                ('createur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créateur du club')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs_valides', to=settings.AUTH_USER_MODEL, verbose_name='Administrateur ayant validé')),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubs',
                'db_table': 'clubs',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='RoleClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(choices=[('president', 'Président'), ('secretaire', 'Secrétaire'), ('tresorier', 'Trésorier'), ('membre', 'Membre')], max_length=50, verbose_name='Intitulé du rôle')),
                ('permissions', models.JSONField(default=list, help_text="Ex: ['ajouter_membre', 'publier', 'valider_cotisation']", verbose_name='Permissions associées')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='clubs.club', verbose_name='Club concerné')),
            ],
            options={
                'verbose_name': 'Rôle dans le club',
                'verbose_name_plural': 'Rôles dans les clubs',
                'db_table': 'roles_club',
                'unique_together': {('libelle', 'club')},
            },
        ),
        migrations.CreateModel(
            name='Adhesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(auto_now_add=True, verbose_name="Date d'adhésion")),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin (si exclu ou parti)')),
                ('est_actif', models.BooleanField(default=True, help_text='False si le membre a quitté ou été exclu du club', verbose_name='Adhésion active')),
                ('ajoute_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres_ajoutes', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par (président)')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adhesions', to='clubs.club', verbose_name='Club')),
                ('roles_club', models.ManyToManyField(blank=True, related_name='adhesions', to='clubs.roleclub', verbose_name='Rôles dans le club')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adhesions', to=settings.AUTH_USER_MODEL, verbose_name='Membre')),
            ],
            options={
                'verbose_name': 'Adhésion',
                'verbose_name_plural': 'Adhésions',
                'db_table': 'adhesions',
                'unique_together': {('utilisateur', 'club')},
            },
        ),
    ]
