# Generated by Django 4.2.19 on 2026-05-27 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre de la publication')),
                ('description', models.TextField(verbose_name='Contenu / Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='publications/images/', verbose_name='Image de la publication')),
                ('date_debut', models.DateTimeField(blank=True, null=True, verbose_name="Date de début de l'événement")),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name="Date de fin de l'événement")),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('publiee', 'Publiée'), ('rejetee', 'Rejetée'), ('archivee', 'Archivée')], default='en_attente', max_length=20, verbose_name='Statut de la publication')),
                ('motif_rejet', models.TextField(blank=True, help_text="Rempli par l'administrateur en cas de rejet", null=True, verbose_name='Motif de rejet')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications_creees', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='clubs.club', verbose_name='Club')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validé/Rejeté par')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'db_table': 'publications',
                'ordering': ['-date_creation'],
            },
        ),
    ]
